DROP TABLE IF EXISTS attendees;
DROP TABLE IF EXISTS analytics;
DROP TABLE IF EXISTS organizers;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS rsvps;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
